# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems :
  - jekyll-paginate

# Setup
title:               Software Automation Framework Support
tagline:             '<br> Initially developed by <b>Carl Nagle</b> for <a href="http://www.sas.com" target="_blank" title="www.sas.com">SAS Institute</a>. Evolves as open source with permission from SAS Institute'
description:         'Framework for software automation.'
url:                 http://safsdev.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              safsdev group
  url:               https://github.com/safsdev
  email:             safsdev@sas.com

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/SAFSDEV/Core
  
sourceforge:
  repo:              https://sourceforge.net/projects/safsdev/